spring.application.name=UniSched

# SQLite
spring.datasource.url=jdbc:sqlite:/home/juanse/Desktop/juans/Personal/Programing/2026/Current Projects/UniSched-API/unisched.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true