name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Dar permisos al Maven Wrapper
        run: chmod +x mvnw

      - name: Ejecutar tests
        run: ./mvnw clean test

      - name: Construir aplicación
        run: ./mvnw package -DskipTests

      - name: Login a GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir y publicar imagen
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/unisched-api:latest

  deploy:
    needs: publish-image
    runs-on: ubuntu-latest

    steps:
      - name: Desplegar en Oracle VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ghcr.io/juanserealpe/unisched-api:latest

            docker stop unisched || true
            docker rm unisched || true

            docker run -d \
            --name unisched \
            --restart unless-stopped \
            --memory=512m \
            --memory-swap=512m \
            --cpus="1.0" \
            -e JAVA_TOOL_OPTIONS="-Xms128m -Xmx384m" \
            --env-file /home/ubuntu/unischedule_project/.env \
            -p 8080:8080 \
            ghcr.io/juanserealpe/unisched-api:latest